version: "3.2"

services:
  app:
    container_name: ${CONTAINER_NAME}
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.development
    env_file: .env
    ports:
      - "${PORT}:8080"
    volumes:
      - .:/app