name: Analyze

on: push
    
jobs:
  build:
    name: Test & Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Test with Coverage
        run : |
          coverage run run setup.py test

      - name: Generate Coverage Reports
        run: |
          coverage report
          coverage xml
      - name: Upload reports
        uses: action/upload-artifact@v2
        with:
          name: reports
          path: |
            coverage.xml
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkoud
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download reports
        uses: action/download-artifact@v2
        with:
          name: reports

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}